CREATE EXCEPTION EX_PRESUPUESTO_VIGENCIA 'Periodo de vigencia invalido para el presupuesto';
CREATE EXCEPTION EX_PRESUPUESTO_TRASLAPADO 'Ya existe un presupuesto activo en el rango seleccionado';
CREATE EXCEPTION EX_PRESUPUESTO_NO_ENCONTRADO 'Presupuesto no encontrado';
CREATE EXCEPTION EX_PRESUPUESTO_USUARIO 'El presupuesto no pertenece al usuario indicado';
CREATE EXCEPTION EX_PRESUPUESTO_ESTADO 'El presupuesto no se encuentra en estado activo';
CREATE EXCEPTION EX_PRESUPUESTO_FUERA_VIGENCIA 'El periodo indicado esta fuera de la vigencia del presupuesto';
CREATE EXCEPTION EX_PRESUPUESTO_NO_FINALIZADO 'El presupuesto aun no ha finalizado su vigencia';
CREATE EXCEPTION EX_TRANSACCION_TIPO_INVALIDO 'Tipo de transaccion invalido';
CREATE EXCEPTION EX_TRANSACCION_MONTO_INVALIDO 'El monto de la transaccion debe ser mayor que cero';
CREATE EXCEPTION EX_TRANSACCION_MES_INVALIDO 'El mes indicado para la transaccion no es valido';
CREATE EXCEPTION EX_TRANSACCION_CATEGORIA_INVALIDA 'La subcategoria no pertenece al usuario o su tipo no coincide';
CREATE EXCEPTION EX_TRANSACCION_OBLIGACION_INVALIDA 'La obligacion indicada no es valida para la transaccion';
CREATE EXCEPTION EX_TRANSACCION_FECHA_FUERA_RANGO 'La fecha de la transaccion cae fuera de la vigencia del presupuesto';
CREATE EXCEPTION EX_OBLIGACION_NO_ENCONTRADA 'Obligacion fija no encontrada';
CREATE EXCEPTION EX_OBLIGACION_SIN_DETALLE 'La obligacion no tiene detalle configurado en el presupuesto';
