CREATE TABLE CATEGORIA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    tipo_categoria VARCHAR(20) NOT NULL,
    category_icon VARCHAR(150),
    color_format VARCHAR(10),
    ui_order INTEGER DEFAULT 0 NOT NULL,
    id_usuario INTEGER NOT NULL,
    estado VARCHAR(20) DEFAULT 'activa' NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER,
    CONSTRAINT CK_CATEGORIA_TIPO CHECK (tipo_categoria IN ('ingreso', 'gasto', 'ahorro')),
    CONSTRAINT CK_CATEGORIA_ESTADO CHECK (estado IN ('activa', 'inactiva'))
)#
