CREATE TABLE DETALLE_PRESUPUESTO (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id INTEGER NOT NULL,  --FK
    subcategoria_id INTEGER NOT NULL, -- FK
    observaciones VARCHAR(500),
    monto_mensual NUMERIC(15,2),
    estado VARCHAR(20) DEFAULT 'activo' NOT NULL,
    modificado_en TIMESTAMP DEFAULT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL
)#