RECEREATE TABLE META_AHORRO (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL, 
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(500),
    monto_objetivo NUMERIC(15,2) NOT NULL CHECK (monto_objetivo > 0),
    monto_acumulado NUMERIC(15,2)  DEFAULT 0 NOT NULL CHECK (monto_acumulado >= 0),
    fecha_objetivo DATE NOT NULL,
    estado INTEGER NOT NULL,
    prioridad INTEGER DEFAULT 3  NOT NULL CHECK (prioridad BETWEEN 1 AND 5),
    promedio_ahorro_mensual NUMERIC(15,2), 
    fecha_inicio DATE  DEFAULT CURRENT_DATE NOT NULL,
    fecha_completada DATE,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    modificado_en TIMESTAMP WITH TIME ZONE DEFAULT NULL ,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL
);