CREATE TABLE OBLIGACION_FIJA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,      -- FK to USUARIO 
    subcategoria_id INTEGER NOT NULL, -- FK to SUBCATEGORIA 
    nombre VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    dia_mes_expiracion INTEGER NOT NULL,
    is_vigente BOOLEAN NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_final DATE,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    modificado_en TIMESTAMP WITH TIME ZONE DEFAULT NULL ,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL
);