# /docker-compose.yaml
services:
  firebird:
    image: firebirdsql/firebird
    restart: always
    environment:
      - FIREBIRD_ROOT_PASSWORD=maria
      - FIREBIRD_USER=maria
      - FIREBIRD_PASSWORD=mariita
      - FIREBIRD_DATABASE=mirror.fdb
    volumes:
      - ./data:/var/lib/firebird/data
      - ./scripts:/opt/firebird/db_scripts
    ports:
      - "3050:3050"

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - firebird
    environment:
      - NODE_ENV=production