CREATE TABLE PRESUPUESTO (
    id_presupuesto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL, --FK 
    nombre_presupuesto VARCHAR(255) NOT NULL,
    anio_inicio INTEGER NOT NULL,
    mes_inicio INTEGER NOT NULL,
    anio_fin INTEGER NOT NULL,
    mes_fin INTEGER NOT NULL,
    total_ingresos_planificados NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_gastos_planificados NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_ahorro_planificado NUMERIC(15,2) NOT NULL DEFAULT 0,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(20) NOT NULL DEFAULT 'borrador',
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por INTEGER,
    CHECK(mes_inicio >= 1 AND mes_inicio <= 12),
    CHECK(mes_fin >= 1 AND mes_fin <= 12),
);