CREATE TABLE CATEGORIA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    tipo_categoria INTEGER NOT NULL,
    category_icon VARCHAR(500) NOT NULL,
    color_format VARCHAR(500) NOT NULL,
    ui_order INTEGER NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    modificado_en TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL
);


CREATE TABLE USUARIO (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    correo_electronico VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    modificado_en TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    salario_mensual_base NUMERIC(15,2) DEFAULT 0 NOT NULL,
    estado VARCHAR(20) DEFAULT 'activo' NOT NULL,
    CHECK (estado IN ('activo', 'inactivo')),
    CHECK (salario_mensual_base >= 0)
);


CREATE TABLE DETALLE_PRESUPUESTO (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id INTEGER NOT NULL,  --FK
    subcategoria_id INTEGER NOT NULL, -- FK
    observaciones VARCHAR(500),
    monto_mensual NUMERIC(15,2),
    modificado_en TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    creado_por INTEGER
);



RECREATE TABLE OBLIGACION_FIJA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,      -- FK to USUARIO 
    subcategoria_id INTEGER NOT NULL, -- FK to SUBCATEGORIA 
    nombre VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    dia_mes_expiracion INTEGER NOT NULL,
    is_vigente BOOLEAN NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_final DATE,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    modificado_en TIMESTAMP WITH TIME ZONE DEFAULT NULL ,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL
);


RECREATE TABLE PRESUPUESTO (
    id_presupuesto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL, --FK USUARIO
    nombre_presupuesto VARCHAR(255) NOT NULL,
    anio_inicio INTEGER NOT NULL,
    mes_inicio INTEGER NOT NULL,
    anio_fin INTEGER NOT NULL,
    mes_fin INTEGER NOT NULL,
    total_ingresos_planificados NUMERIC(15,2) DEFAULT 0 NOT NULL,
    total_gastos_planificados NUMERIC(15,2) DEFAULT 0 NOT NULL,
    total_ahorro_planificado NUMERIC(15,2) DEFAULT 0 NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL,
    estado VARCHAR(20) DEFAULT 'borrador' NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    modificado_en TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL,
    CHECK(mes_inicio >= 1 AND mes_inicio <= 12),
    CHECK(mes_fin >= 1 AND mes_fin <= 12)
);


RECREATE TABLE SUBCATEGORIA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id INTEGER NOT NULL, -- FK
    nombre VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    is_default BOOLEAN NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    modificado_en TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL
);

RECREATE TABLE TRANSACCIONES (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,      --FK
    presupuesto_id INTEGER NOT NULL,  --FK
    anio INTEGER NOT NULL,
    mes INTEGER NOT NULL,
    subcategoria_id INTEGER NOT NULL, -- FK
    obligacion_id INTEGER,            -- FK
    descripcion VARCHAR(500),
    monto NUMERIC(15,2),
    fecha DATE,
    no_factura VARCHAR(500),
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
    modificado_en TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL
);