CREATE TABLE CATEGORIA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(500) NOT NULL,
    description VARCHAR(500),
    category_type INTEGER NOT NULL,
    category_icon VARCHAR(500) NOT NULL,
    color_format VARCHAR(500) NOT NULL,
    ui_order INTEGER NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por INTEGER
);CREATE TABLE DETALLE_PRESUPUESTO (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id INTEGER NOT NULL,  --FK
    subcategoria_id INTEGER NOT NULL, -- FK
    observaciones VARCHAR(500),
    monto_mensual DOUBLE PRECISION,
    modificado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por INTEGER
);CREATE TABLE USUARIO (
    id_usuario INTEGER NOT NULL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    correo_electronico VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    salario_mensual_base NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    estado VARCHAR(20) NOT NULL DEFAULT 'activo',
    CHECK (estado IN ('activo', 'inactivo')),
    CHECK (salario_mensual_base >= 0)
);

CREATE TABLE PRESUPUESTO (
    id_presupuesto INTEGER NOT NULL PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    nombre_presupuesto VARCHAR(255) NOT NULL,
    anio_inicio INTEGER NOT NULL,
    mes_inicio INTEGER NOT NULL,
    anio_fin INTEGER NOT NULL,
    mes_fin INTEGER NOT NULL,
    total_ingresos_planificados NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    total_gastos_planificados NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    total_ahorro_planificado NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(20) NOT NULL DEFAULT 'borrador',
    CHECK (mes_inicio BETWEEN 1 AND 12),
    CHECK (mes_fin BETWEEN 1 AND 12),
    CHECK (estado IN ('activo', 'cerrado', 'borrador')),
    CHECK (total_ingresos_planificados >= 0 AND 
        total_gastos_planificados >= 0 AND 
        total_ahorro_planificado >= 0)
);

ALTER TABLE PRESUPUESTO 
ADD CONSTRAINT fk_PRESUPUESTO_id_usuario 
FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario);
CREATE TABLE PRESUPUESTO (
    id_presupuesto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL, --FK 
    nombre_presupuesto VARCHAR(255) NOT NULL,
    anio_inicio INTEGER NOT NULL,
    mes_inicio INTEGER NOT NULL,
    anio_fin INTEGER NOT NULL,
    mes_fin INTEGER NOT NULL,
    total_ingresos_planificados NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_gastos_planificados NUMERIC(15,2) NOT NULL DEFAULT 0,
    total_ahorro_planificado NUMERIC(15,2) NOT NULL DEFAULT 0,
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(20) NOT NULL DEFAULT 'borrador',
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por INTEGER,
    CHECK(mes_inicio >= 1 AND mes_inicio <= 12),
    CHECK(mes_fin >= 1 AND mes_fin <= 12),
);CREATE TABLE SUBCATEGORIA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id INTEGER NOT NULL, -- FK
    nombre VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    is_default BOOLEAN NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por INTEGER
);
CREATE TABLE TRANSACCIONES (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,      --FK
    presupuesto_id INTEGER NOT NULL,  --FK
    anio INTEGER NOT NULL,
    mes INTEGER NOT NULL,
    subcategoria_id INTEGER NOT NULL, -- FK
    obligacion_id INTEGER,            -- FK
    descripcion VARCHAR(500),
    monto DOUBLE PRECISION,
    fecha DATE,
    no_factura VARCHAR(500),
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por INTEGER
);CREATE TABLE USUARIO (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    correo_electronico VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMP WITH TIME ZONE NOT NULL,
    salario_mensual_base NUMERIC(15,2) DEFAULT 0 NOT NULL,
    estado VARCHAR(20) DEFAULT 'activo' NOT NULL,
    CHECK (estado IN ('activo', 'inactivo')),
    CHECK (salario_mensual_base >= 0)
);
