SET TERM #;

CREATE TABLE CATEGORIA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    tipo_categoria VARCHAR(20) NOT NULL,
    category_icon VARCHAR(150),
    color_format VARCHAR(10),
    ui_order INTEGER DEFAULT 0 NOT NULL,
    id_usuario INTEGER NOT NULL,
    estado VARCHAR(20) DEFAULT 'activa' NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER,
    CONSTRAINT CK_CATEGORIA_TIPO CHECK (tipo_categoria IN ('ingreso', 'gasto', 'ahorro')),
    CONSTRAINT CK_CATEGORIA_ESTADO CHECK (estado IN ('activa', 'inactiva'))
)#


CREATE TABLE DETALLE_PRESUPUESTO (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id INTEGER NOT NULL,  --FK
    subcategoria_id INTEGER NOT NULL, -- FK
    observaciones VARCHAR(500),
    monto_mensual NUMERIC(15,2),
    estado VARCHAR(20) DEFAULT 'activo' NOT NULL,
    modificado_en TIMESTAMP DEFAULT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL
)#

CREATE TABLE META_AHORRO (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL, 
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(500),
    monto_objetivo NUMERIC(15,2) NOT NULL CHECK (monto_objetivo > 0),
    monto_acumulado NUMERIC(15,2)  DEFAULT 0 NOT NULL CHECK (monto_acumulado >= 0),
    fecha_objetivo DATE NOT NULL,
    estado VARCHAR(20) DEFAULT 'activo' NOT NULL,
    prioridad INTEGER DEFAULT 3  NOT NULL CHECK (prioridad BETWEEN 1 AND 5),
    promedio_ahorro_mensual NUMERIC(15,2), 
    fecha_inicio DATE  DEFAULT CURRENT_DATE NOT NULL,
    fecha_completada DATE,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    modificado_en TIMESTAMP DEFAULT NULL ,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL
)#

CREATE TABLE OBLIGACION_FIJA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,      -- FK to USUARIO 
    subcategoria_id INTEGER NOT NULL, -- FK to SUBCATEGORIA 
    nombre VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    dia_mes_expiracion INTEGER NOT NULL,
    is_vigente BOOLEAN NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_final DATE,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    modificado_en TIMESTAMP DEFAULT NULL ,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL
)#

CREATE TABLE PRESUPUESTO (
    id_presupuesto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL, --FK USUARIO
    nombre_presupuesto VARCHAR(255) NOT NULL,
    anio_inicio INTEGER NOT NULL,
    mes_inicio INTEGER NOT NULL,
    anio_fin INTEGER NOT NULL,
    mes_fin INTEGER NOT NULL,
    total_ingresos_planificados NUMERIC(15,2) DEFAULT 0 NOT NULL,
    total_gastos_planificados NUMERIC(15,2) DEFAULT 0 NOT NULL,
    total_ahorro_planificado NUMERIC(15,2) DEFAULT 0 NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    estado VARCHAR(20) DEFAULT 'borrador' NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    modificado_en TIMESTAMP DEFAULT NULL,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL,
    CHECK(mes_inicio >= 1 AND mes_inicio <= 12),
    CHECK(mes_fin >= 1 AND mes_fin <= 12)
)#

CREATE TABLE SUBCATEGORIA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id INTEGER NOT NULL,
    nombre VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    is_default BOOLEAN DEFAULT FALSE NOT NULL,
    estado VARCHAR(20) DEFAULT 'activa' NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER,
    CONSTRAINT CK_SUBCATEGORIA_ESTADO CHECK (estado IN ('activa', 'inactiva')),
    CONSTRAINT CK_SUBCATEGORIA_DEFAULT CHECK (is_default IN (TRUE, FALSE))
)#


CREATE TABLE TRANSACCIONES (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,      --FK
    presupuesto_id INTEGER NOT NULL,  --FK
    anio INTEGER NOT NULL,
    mes INTEGER NOT NULL,
    subcategoria_id INTEGER NOT NULL, -- FK
    obligacion_id INTEGER,            -- FK
    tipo VARCHAR(20) NOT NULL,
    descripcion VARCHAR(500),
    monto NUMERIC(15,2),
    fecha DATE,
    metodo_pago VARCHAR(30),
    no_factura VARCHAR(500),
    observaciones VARCHAR(500),
    estado VARCHAR(20) DEFAULT 'activo' NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    modificado_en TIMESTAMP DEFAULT NULL,
    creado_por INTEGER,
    modificado_por INTEGER DEFAULT NULL,
    CHECK (mes BETWEEN 1 AND 12),
    CHECK (tipo IN ('ingreso', 'gasto', 'ahorro')),
    CHECK (estado IN ('activo', 'inactivo'))
)#


CREATE TABLE USUARIO (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    correo_electronico VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    modificado_en TIMESTAMP DEFAULT NULL,
    creador_por INTEGER DEFAULT NULL,
    modificado_por INTEGER DEFAULT NULL,
    salario_mensual_base NUMERIC(15,2) DEFAULT 0 NOT NULL,
    estado VARCHAR(20) DEFAULT 'activo' NOT NULL,
    CHECK (estado IN ('activo', 'inactivo')),
    CHECK (salario_mensual_base >= 0)
)#


CREATE PROCEDURE SP_INSERTAR_CATEGORIA (
    p_id_usuario INTEGER,
    p_nombre VARCHAR(500),
    p_descripcion VARCHAR(500),
    p_tipo_categoria VARCHAR(20),
    p_category_icon VARCHAR(150),
    p_color_format VARCHAR(10),
    p_ui_order INTEGER,
    p_estado VARCHAR(20),
    p_creado_por INTEGER
)
RETURNS (
    id_categoria INTEGER
)
AS
BEGIN
    INSERT INTO CATEGORIA (
        nombre,
        descripcion,
        tipo_categoria,
        category_icon,
        color_format,
        ui_order,
        id_usuario,
        estado,
        creado_por,
        creado_en
    )
    VALUES (
        :p_nombre,
        :p_descripcion,
        :p_tipo_categoria,
        :p_category_icon,
        :p_color_format,
        COALESCE(:p_ui_order, 0),
        :p_id_usuario,
        COALESCE(:p_estado, 'activa'),
        :p_creado_por,
        CURRENT_TIMESTAMP
    )
    RETURNING id INTO id_categoria;
    SUSPEND;
END#


CREATE PROCEDURE SP_ELIMINAR_CATEGORIA (
    p_id_categoria INTEGER
)
AS
DECLARE VARIABLE v_subcategorias_activas INTEGER;
BEGIN
    SELECT COUNT(*)
    FROM SUBCATEGORIA
    WHERE categoria_id = :p_id_categoria
      AND estado = 'activa'
      AND is_default = FALSE
    INTO :v_subcategorias_activas;

    IF (v_subcategorias_activas > 0) THEN
        EXCEPTION ex_categoria_con_subcategorias;

    UPDATE SUBCATEGORIA
    SET estado = 'inactiva',
        modificado_en = CURRENT_TIMESTAMP
    WHERE categoria_id = :p_id_categoria;

    UPDATE CATEGORIA
    SET estado = 'inactiva',
        modificado_en = CURRENT_TIMESTAMP
    WHERE id = :p_id_categoria;
END#


CREATE EXCEPTION EX_CATEGORIA_CON_SUBCATEGORIAS 'La categoria tiene subcategorias activas adicionales';
CREATE EXCEPTION EX_CATEGORIA_NO_DEFAULT 'No existe subcategoria por defecto';
CREATE EXCEPTION EX_CATEGORIA_NO_ENCONTRADA 'Categoria no encontrada';
CREATE EXCEPTION EX_SUBCATEGORIA_DEFAULT_EXISTENTE 'Ya existe una subcategoria por defecto';
CREATE EXCEPTION EX_CATEGORIA_SIN_SUBCATEGORIA 'La categoria debe mantener al menos una subcategoria activa';
CREATE EXCEPTION EX_SUBCATEGORIA_NO_ENCONTRADA 'Subcategoria no encontrada';
CREATE EXCEPTION EX_SUBCATEGORIA_DEFAULT_NO_ELIMINAR 'No se puede eliminar la subcategoria por defecto';
CREATE EXCEPTION EX_SUBCATEGORIA_USADA_DETALLE 'La subcategoria se utiliza en detalle de presupuesto';
CREATE EXCEPTION EX_SUBCATEGORIA_USADA_TRANSACCION 'La subcategoria se utiliza en transacciones';


CREATE PROCEDURE SP_LISTAR_CATEGORIAS (
    p_id_usuario INTEGER,
    p_tipo_categoria VARCHAR(20)
)
RETURNS (
    id INTEGER,
    id_usuario INTEGER,
    nombre VARCHAR(500),
    descripcion VARCHAR(500),
    tipo_categoria VARCHAR(20),
    category_icon VARCHAR(150),
    color_format VARCHAR(10),
    ui_order INTEGER,
    estado VARCHAR(20),
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    FOR SELECT
        id,
        id_usuario,
        nombre,
        descripcion,
        tipo_categoria,
        category_icon,
        color_format,
        ui_order,
        estado,
        creado_en,
        modificado_en,
        creado_por,
        modificado_por
    FROM
        CATEGORIA
    WHERE
        id_usuario = :p_id_usuario
        AND (:p_tipo_categoria IS NULL OR tipo_categoria = :p_tipo_categoria)
    ORDER BY
        ui_order,
        nombre
    INTO
        :id,
        :id_usuario,
        :nombre,
        :descripcion,
        :tipo_categoria,
        :category_icon,
        :color_format,
        :ui_order,
        :estado,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por
    DO
    BEGIN
        SUSPEND;
    END
END#


CREATE PROCEDURE SP_CONSULTAR_CATEGORIA (
    p_id_categoria INTEGER
)
RETURNS (
    id INTEGER,
    id_usuario INTEGER,
    nombre VARCHAR(500),
    descripcion VARCHAR(500),
    tipo_categoria VARCHAR(20),
    category_icon VARCHAR(150),
    color_format VARCHAR(10),
    ui_order INTEGER,
    estado VARCHAR(20),
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    FOR SELECT
        id,
        id_usuario,
        nombre,
        descripcion,
        tipo_categoria,
        category_icon,
        color_format,
        ui_order,
        estado,
        creado_en,
        modificado_en,
        creado_por,
        modificado_por
    FROM
        CATEGORIA
    WHERE
        id = :p_id_categoria
    INTO
        :id,
        :id_usuario,
        :nombre,
        :descripcion,
        :tipo_categoria,
        :category_icon,
        :color_format,
        :ui_order,
        :estado,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por
    DO
    BEGIN
        SUSPEND;
    END
END#


CREATE PROCEDURE SP_ACTUALIZAR_CATEGORIA (
    p_id_categoria INTEGER,
    p_nombre VARCHAR(500),
    p_descripcion VARCHAR(500),
    p_category_icon VARCHAR(150),
    p_color_format VARCHAR(10),
    p_ui_order INTEGER,
    p_estado VARCHAR(20),
    p_modificado_por INTEGER
) AS
BEGIN
    UPDATE CATEGORIA
    SET nombre = COALESCE(:p_nombre, nombre),
        descripcion = COALESCE(:p_descripcion, descripcion),
        category_icon = COALESCE(:p_category_icon, category_icon),
        color_format = COALESCE(:p_color_format, color_format),
        ui_order = COALESCE(:p_ui_order, ui_order),
        estado = COALESCE(:p_estado, estado),
        modificado_por = :p_modificado_por,
        modificado_en = CURRENT_TIMESTAMP
    WHERE id = :p_id_categoria;
END#


CREATE PROCEDURE SP_INSERTAR_DETALLE_PRESUPUESTO (
    p_id_presupuesto INTEGER,
    p_id_subcategoria INTEGER,
    p_monto_mensual NUMERIC(15, 2),
    p_observaciones VARCHAR(500),
    p_creado_por INTEGER
)
RETURNS (
    id_detalle_presupuesto INTEGER
)
AS
BEGIN
    INSERT INTO DETALLE_PRESUPUESTO (
        presupuesto_id,
        subcategoria_id,
        monto_mensual,
        observaciones,
        estado,
        creado_en,
        creado_por
    )
    VALUES (
        :p_id_presupuesto,
        :p_id_subcategoria,
        :p_monto_mensual,
        :p_observaciones,
        'activo',
        CURRENT_TIMESTAMP,
        :p_creado_por
    )
    RETURNING id INTO id_detalle_presupuesto;

    SUSPEND;
END#



CREATE PROCEDURE SP_ELIMINAR_DETALLE_PRESUPUESTO (
    p_id_detalle_presupuesto INTEGER,
    p_modificado_por INTEGER
)
AS
BEGIN
    UPDATE DETALLE_PRESUPUESTO
    SET estado = 'inactivo',
        modificado_en = CURRENT_TIMESTAMP,
        modificado_por = :p_modificado_por
    WHERE id = :p_id_detalle_presupuesto;
END#



CREATE PROCEDURE SP_LISTAR_DETALLE_PRESUPUESTO (
    p_id_presupuesto INTEGER
)
RETURNS (
    id INTEGER,
    presupuesto_id INTEGER,
    subcategoria_id INTEGER,
    monto_mensual NUMERIC(15, 2),
    observaciones VARCHAR(500),
    estado VARCHAR(20),
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    FOR SELECT 
        id,
        presupuesto_id,
        subcategoria_id,
        monto_mensual,
        observaciones,
        estado,
        creado_en,
        modificado_en,
        creado_por,
        modificado_por
    FROM DETALLE_PRESUPUESTO
    WHERE presupuesto_id = :p_id_presupuesto
    INTO 
        :id,
        :presupuesto_id,
        :subcategoria_id,
        :monto_mensual,
        :observaciones,
        :estado,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por
    DO
        SUSPEND;
END#



CREATE PROCEDURE SP_CONSULTAR_DETALLE_PRESUPUESTO (
    p_id_detalle_presupuesto INTEGER
)
RETURNS (
    id INTEGER,
    presupuesto_id INTEGER,
    subcategoria_id INTEGER,
    monto_mensual NUMERIC(15, 2),
    observaciones VARCHAR(500),
    estado VARCHAR(20),
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    FOR SELECT 
        id,
        presupuesto_id,
        subcategoria_id,
        monto_mensual,
        observaciones,
        estado,
        creado_en,
        modificado_en,
        creado_por,
        modificado_por
    FROM DETALLE_PRESUPUESTO
    WHERE id = :p_id_detalle_presupuesto
    INTO 
        :id,
        :presupuesto_id,
        :subcategoria_id,
        :monto_mensual,
        :observaciones,
        :estado,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por
    DO
        SUSPEND;
END#



CREATE PROCEDURE SP_ACTUALIZAR_DETALLE_PRESUPUESTO (
    p_id_detalle_presupuesto INTEGER,
    p_monto_mensual NUMERIC(15, 2),
    p_observaciones VARCHAR(500),
    p_modificado_por INTEGER
)
AS
BEGIN
    UPDATE DETALLE_PRESUPUESTO
    SET monto_mensual = :p_monto_mensual,
        observaciones = :p_observaciones,
        modificado_en = CURRENT_TIMESTAMP,
        modificado_por = :p_modificado_por
    WHERE id = :p_id_detalle_presupuesto;
END#


-- SP_INSERTAR_META_AHORRO
-- Inserta un nuevo registro en la tabla META_AHORRO y retorna el id generado.
CREATE PROCEDURE SP_INSERTAR_META_AHORRO (
    p_id_usuario INTEGER,
    p_nombre VARCHAR(255),
    p_descripcion VARCHAR(500),
    p_monto_objetivo NUMERIC(15,2),
    p_monto_acumulado NUMERIC(15,2),
    p_fecha_objetivo DATE,
    p_estado VARCHAR(20),
    p_prioridad INTEGER,
    p_promedio_ahorro_mensual NUMERIC(15,2),
    p_fecha_inicio DATE,
    p_fecha_completada DATE,
    p_creado_por INTEGER
)
RETURNS (
    id_meta_ahorro INTEGER
)
AS
BEGIN
    INSERT INTO META_AHORRO (
        id_usuario,
        nombre,
        descripcion,
        monto_objetivo,
        monto_acumulado,
        fecha_objetivo,
        estado,
        prioridad,
        promedio_ahorro_mensual,
        fecha_inicio,
        fecha_completada,
        creado_en,
        creado_por
    )
    VALUES (
        :p_id_usuario,
        :p_nombre,
        :p_descripcion,
        :p_monto_objetivo,
        :p_monto_acumulado,
        :p_fecha_objetivo,
        :p_estado,
        :p_prioridad,
        :p_promedio_ahorro_mensual,
        :p_fecha_inicio,
        :p_fecha_completada,
        CURRENT_TIMESTAMP,
        :p_creado_por
    )
    RETURNING id INTO id_meta_ahorro;
    SUSPEND;
END#


-- SP_ELIMINAR_META_AHORRO
-- Realiza un soft delete actualizando el campo estado a 'inactivo' en la tabla META_AHORRO.
CREATE PROCEDURE SP_ELIMINAR_META_AHORRO (
    p_id_meta_ahorro INTEGER
)
AS
BEGIN
    UPDATE META_AHORRO
    SET estado = 'inactivo',
        modificado_en = CURRENT_TIMESTAMP
    WHERE id = :p_id_meta_ahorro;
END#


-- SP_LISTAR_META_AHORRO
-- Devuelve todos los registros de la tabla META_AHORRO.
CREATE PROCEDURE SP_LISTAR_META_AHORRO
RETURNS (
    id INTEGER,
    id_usuario INTEGER,
    nombre VARCHAR(255),
    descripcion VARCHAR(500),
    monto_objetivo NUMERIC(15,2),
    monto_acumulado NUMERIC(15,2),
    fecha_objetivo DATE,
    estado VARCHAR(20),
    prioridad INTEGER,
    promedio_ahorro_mensual NUMERIC(15,2),
    fecha_inicio DATE,
    fecha_completada DATE,
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    FOR SELECT 
        id,
        id_usuario,
        nombre,
        descripcion,
        monto_objetivo,
        monto_acumulado,
        fecha_objetivo,
        estado,
        prioridad,
        promedio_ahorro_mensual,
        fecha_inicio,
        fecha_completada,
        creado_en,
        modificado_en,
        creado_por,
        modificado_por
    FROM META_AHORRO
    INTO 
        :id,
        :id_usuario,
        :nombre,
        :descripcion,
        :monto_objetivo,
        :monto_acumulado,
        :fecha_objetivo,
        :estado,
        :prioridad,
        :promedio_ahorro_mensual,
        :fecha_inicio,
        :fecha_completada,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por
    DO
        SUSPEND;
END#


-- SP_CONSULTAR_META_AHORRO
-- Devuelve un único registro de la tabla META_AHORRO según su id.
CREATE PROCEDURE SP_CONSULTAR_META_AHORRO (
    p_id_meta_ahorro INTEGER
)
RETURNS (
    id INTEGER,
    id_usuario INTEGER,
    nombre VARCHAR(255),
    descripcion VARCHAR(500),
    monto_objetivo NUMERIC(15,2),
    monto_acumulado NUMERIC(15,2),
    fecha_objetivo DATE,
    estado VARCHAR(20),
    prioridad INTEGER,
    promedio_ahorro_mensual NUMERIC(15,2),
    fecha_inicio DATE,
    fecha_completada DATE,
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    SELECT 
        id,
        id_usuario,
        nombre,
        descripcion,
        monto_objetivo,
        monto_acumulado,
        fecha_objetivo,
        estado,
        prioridad,
        promedio_ahorro_mensual,
        fecha_inicio,
        fecha_completada,
        creado_en,
        modificado_en,
        creado_por,
        modificado_por
    FROM META_AHORRO
    WHERE id = :p_id_meta_ahorro
    INTO 
        :id,
        :id_usuario,
        :nombre,
        :descripcion,
        :monto_objetivo,
        :monto_acumulado,
        :fecha_objetivo,
        :estado,
        :prioridad,
        :promedio_ahorro_mensual,
        :fecha_inicio,
        :fecha_completada,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por;
    IF (id IS NOT NULL) THEN
        SUSPEND;
END#


-- SP_ACTUALIZAR_META_AHORRO
-- Actualiza un registro existente en la tabla META_AHORRO.
CREATE PROCEDURE SP_ACTUALIZAR_META_AHORRO (
    p_id_meta_ahorro INTEGER,
    p_id_usuario INTEGER,
    p_nombre VARCHAR(255),
    p_descripcion VARCHAR(500),
    p_monto_objetivo NUMERIC(15,2),
    p_monto_acumulado NUMERIC(15,2),
    p_fecha_objetivo DATE,
    p_estado estado VARCHAR(20),
    p_prioridad INTEGER,
    p_promedio_ahorro_mensual NUMERIC(15,2),
    p_fecha_inicio DATE,
    p_fecha_completada DATE,
    p_modificado_por INTEGER
)
AS
BEGIN
    UPDATE META_AHORRO
    SET id_usuario = :p_id_usuario,
        nombre = :p_nombre,
        descripcion = :p_descripcion,
        monto_objetivo = :p_monto_objetivo,
        monto_acumulado = :p_monto_acumulado,
        fecha_objetivo = :p_fecha_objetivo,
        estado = :p_estado,
        prioridad = :p_prioridad,
        promedio_ahorro_mensual = :p_promedio_ahorro_mensual,
        fecha_inicio = :p_fecha_inicio,
        fecha_completada = :p_fecha_completada,
        modificado_en = CURRENT_TIMESTAMP,
        modificado_por = :p_modificado_por
    WHERE id = :p_id_meta_ahorro;
END#



CREATE PROCEDURE SP_INSERTAR_OBLIGACION_FIJA (
    p_id_usuario INTEGER,
    p_subcategoria_id INTEGER,
    p_nombre VARCHAR(500),
    p_descripcion VARCHAR(500),
    p_dia_mes_expiracion INTEGER,
    p_is_vigente BOOLEAN,
    p_fecha_inicio DATE,
    p_fecha_final DATE,
    p_creado_por INTEGER
)
RETURNS (
    id_obligacion_fija INTEGER
)
AS
BEGIN
    INSERT INTO OBLIGACION_FIJA (
        id_usuario,
        subcategoria_id,
        nombre,
        descripcion,
        dia_mes_expiracion,
        is_vigente,
        fecha_inicio,
        fecha_final,
        creado_en,
        creado_por
    )
    VALUES (
        :p_id_usuario,
        :p_subcategoria_id,
        :p_nombre,
        :p_descripcion,
        :p_dia_mes_expiracion,
        :p_is_vigente,
        :p_fecha_inicio,
        :p_fecha_final,
        CURRENT_TIMESTAMP,
        :p_creado_por
    )
    RETURNING id INTO id_obligacion_fija;
    SUSPEND;
END#

CREATE PROCEDURE SP_ELIMINAR_OBLIGACION_FIJA (
    p_id_obligacion_fija INTEGER
)
AS
BEGIN
    UPDATE OBLIGACION_FIJA
    SET estado = 'inactivo',
        modificado_en = CURRENT_TIMESTAMP
    WHERE id = :p_id_obligacion_fija;
END#


CREATE PROCEDURE SP_LISTAR_OBLIGACION_FIJA
RETURNS (
    id INTEGER,
    id_usuario INTEGER,
    subcategoria_id INTEGER,
    nombre VARCHAR(500),
    descripcion VARCHAR(500),
    dia_mes_expiracion INTEGER,
    is_vigente BOOLEAN,
    fecha_inicio DATE,
    fecha_final DATE,
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    FOR SELECT 
        id,
        id_usuario,
        subcategoria_id,
        nombre,
        descripcion,
        dia_mes_expiracion,
        is_vigente,
        fecha_inicio,
        fecha_final,
        creado_en,
        modificado_en,
        creado_por,
        modificado_por
    FROM OBLIGACION_FIJA
    INTO 
        :id,
        :id_usuario,
        :subcategoria_id,
        :nombre,
        :descripcion,
        :dia_mes_expiracion,
        :is_vigente,
        :fecha_inicio,
        :fecha_final,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por
    DO
        SUSPEND;
END#



CREATE PROCEDURE SP_CONSULTAR_OBLIGACION_FIJA (
    p_id_obligacion_fija INTEGER
)
RETURNS (
    id INTEGER,
    id_usuario INTEGER,
    subcategoria_id INTEGER,
    nombre VARCHAR(500),
    descripcion VARCHAR(500),
    dia_mes_expiracion INTEGER,
    is_vigente BOOLEAN,
    fecha_inicio DATE,
    fecha_final DATE,
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    SELECT 
        id,
        id_usuario,
        subcategoria_id,
        nombre,
        descripcion,
        dia_mes_expiracion,
        is_vigente,
        fecha_inicio,
        fecha_final,
        creado_en,
        modificado_en,
        creado_por,
        modificado_por
    FROM OBLIGACION_FIJA
    WHERE id = :p_id_obligacion_fija
    INTO 
        :id,
        :id_usuario,
        :subcategoria_id,
        :nombre,
        :descripcion,
        :dia_mes_expiracion,
        :is_vigente,
        :fecha_inicio,
        :fecha_final,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por;
    IF (id IS NOT NULL) THEN
        SUSPEND;
END#


CREATE PROCEDURE SP_ACTUALIZAR_OBLIGACION_FIJA (
    p_id_obligacion_fija INTEGER,
    p_id_usuario INTEGER,
    p_subcategoria_id INTEGER,
    p_nombre VARCHAR(500),
    p_descripcion VARCHAR(500),
    p_dia_mes_expiracion INTEGER,
    p_is_vigente BOOLEAN,
    p_fecha_inicio DATE,
    p_fecha_final DATE,
    p_modificado_por INTEGER
)
AS
BEGIN
    UPDATE OBLIGACION_FIJA
    SET id_usuario = :p_id_usuario,
        subcategoria_id = :p_subcategoria_id,
        nombre = :p_nombre,
        descripcion = :p_descripcion,
        dia_mes_expiracion = :p_dia_mes_expiracion,
        is_vigente = :p_is_vigente,
        fecha_inicio = :p_fecha_inicio,
        fecha_final = :p_fecha_final,
        modificado_en = CURRENT_TIMESTAMP,
        modificado_por = :p_modificado_por
    WHERE id = :p_id_obligacion_fija;
END#


CREATE PROCEDURE SP_INSERTAR_PRESUPUESTO (
    id_usuario INTEGER,
    nombre_presupuesto VARCHAR(255),
    anio_inicio INTEGER,
    mes_inicio INTEGER,
    anio_fin INTEGER,
    mes_fin INTEGER,
    total_ingresos_planificados NUMERIC(15,2),
    total_gastos_planificados NUMERIC(15,2),
    total_ahorro_planificado NUMERIC(15,2),
    fecha_creacion TIMESTAMP,
    estado VARCHAR(20),
    creado_en TIMESTAMP,
    creado_por INTEGER
)
RETURNS (
    nuevo_id_presupuesto INTEGER
)
AS
BEGIN
    INSERT INTO PRESUPUESTO (
        id_usuario, nombre_presupuesto, anio_inicio, mes_inicio, anio_fin, mes_fin,
        total_ingresos_planificados, total_gastos_planificados, total_ahorro_planificado,
        fecha_creacion, estado, creado_en, creado_por
    )
    VALUES (
        :id_usuario, :nombre_presupuesto, :anio_inicio, :mes_inicio, :anio_fin, :mes_fin,
        :total_ingresos_planificados, :total_gastos_planificados, :total_ahorro_planificado,
        :fecha_creacion, :estado, :creado_en, :creado_por
    )
    RETURNING id_presupuesto INTO nuevo_id_presupuesto;
    SUSPEND;
END#


CREATE PROCEDURE SP_ELIMINAR_PRESUPUESTO (
    id_presupuesto INTEGER
)
AS
BEGIN
    DELETE FROM PRESUPUESTO
    WHERE id_presupuesto = :id_presupuesto;
END#

CREATE EXCEPTION EX_PRESUPUESTO_VIGENCIA 'Periodo de vigencia invalido para el presupuesto';
CREATE EXCEPTION EX_PRESUPUESTO_TRASLAPADO 'Ya existe un presupuesto activo en el rango seleccionado';
CREATE EXCEPTION EX_PRESUPUESTO_NO_ENCONTRADO 'Presupuesto no encontrado';
CREATE EXCEPTION EX_PRESUPUESTO_USUARIO 'El presupuesto no pertenece al usuario indicado';
CREATE EXCEPTION EX_PRESUPUESTO_ESTADO 'El presupuesto no se encuentra en estado activo';
CREATE EXCEPTION EX_PRESUPUESTO_FUERA_VIGENCIA 'El periodo indicado esta fuera de la vigencia del presupuesto';
CREATE EXCEPTION EX_PRESUPUESTO_NO_FINALIZADO 'El presupuesto aun no ha finalizado su vigencia';
CREATE EXCEPTION EX_TRANSACCION_TIPO_INVALIDO 'Tipo de transaccion invalido';
CREATE EXCEPTION EX_TRANSACCION_MONTO_INVALIDO 'El monto de la transaccion debe ser mayor que cero';
CREATE EXCEPTION EX_TRANSACCION_MES_INVALIDO 'El mes indicado para la transaccion no es valido';
CREATE EXCEPTION EX_TRANSACCION_CATEGORIA_INVALIDA 'La subcategoria no pertenece al usuario o su tipo no coincide';
CREATE EXCEPTION EX_TRANSACCION_OBLIGACION_INVALIDA 'La obligacion indicada no es valida para la transaccion';
CREATE EXCEPTION EX_TRANSACCION_FECHA_FUERA_RANGO 'La fecha de la transaccion cae fuera de la vigencia del presupuesto';
CREATE EXCEPTION EX_OBLIGACION_NO_ENCONTRADA 'Obligacion fija no encontrada';
CREATE EXCEPTION EX_OBLIGACION_SIN_DETALLE 'La obligacion no tiene detalle configurado en el presupuesto';


CREATE PROCEDURE SP_LISTAR_PRESUPUESTOS (p_id_usuario INTEGER, p_estado VARCHAR(20))
RETURNS (
    id_presupuesto INTEGER,
    id_usuario INTEGER,
    nombre_presupuesto VARCHAR(255),
    anio_inicio INTEGER,
    mes_inicio INTEGER,
    anio_fin INTEGER,
    mes_fin INTEGER,
    total_ingresos_planificados NUMERIC(15,2),
    total_gastos_planificados NUMERIC(15,2),
    total_ahorro_planificado NUMERIC(15,2),
    fecha_creacion TIMESTAMP,
    estado VARCHAR(20),
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    FOR SELECT 
        id_presupuesto, id_usuario, nombre_presupuesto, anio_inicio, mes_inicio, anio_fin, mes_fin,
        total_ingresos_planificados, total_gastos_planificados, total_ahorro_planificado,
        fecha_creacion, estado, creado_en, modificado_en, creado_por, modificado_por
    FROM PRESUPUESTO
    WHERE id_usuario = :p_id_usuario
      AND (:p_estado IS NULL OR estado = :p_estado)
    INTO 
        :id_presupuesto, :id_usuario, :nombre_presupuesto, :anio_inicio, :mes_inicio, :anio_fin, :mes_fin,
        :total_ingresos_planificados, :total_gastos_planificados, :total_ahorro_planificado,
        :fecha_creacion, :estado, :creado_en, :modificado_en, :creado_por, :modificado_por
    DO
    BEGIN
        SUSPEND;
    END
END#


CREATE PROCEDURE SP_CONSULTAR_PRESUPUESTO (
    id_presupuesto INTEGER
)
RETURNS (
    id_presupuesto INTEGER,
    id_usuario INTEGER,
    nombre_presupuesto VARCHAR(255),
    anio_inicio INTEGER,
    mes_inicio INTEGER,
    anio_fin INTEGER,
    mes_fin INTEGER,
    total_ingresos_planificados NUMERIC(15,2),
    total_gastos_planificados NUMERIC(15,2),
    total_ahorro_planificado NUMERIC(15,2),
    fecha_creacion TIMESTAMP,
    estado VARCHAR(20),
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    FOR SELECT 
        id_presupuesto, id_usuario, nombre_presupuesto, anio_inicio, mes_inicio, anio_fin, mes_fin,
        total_ingresos_planificados, total_gastos_planificados, total_ahorro_planificado,
        fecha_creacion, estado, creado_en, modificado_en, creado_por, modificado_por
    FROM PRESUPUESTO
    WHERE id_presupuesto = :id_presupuesto
    INTO 
        :id_presupuesto, :id_usuario, :nombre_presupuesto, :anio_inicio, :mes_inicio, :anio_fin, :mes_fin,
        :total_ingresos_planificados, :total_gastos_planificados, :total_ahorro_planificado,
        :fecha_creacion, :estado, :creado_en, :modificado_en, :creado_por, :modificado_por
    DO
    BEGIN
        SUSPEND;
    END
END#


CREATE PROCEDURE SP_CALCULAR_BALANCE_MENSUAL (
    p_id_usuario INTEGER,
    p_id_presupuesto INTEGER,
    p_anio INTEGER,
    p_mes INTEGER
)
RETURNS (
    total_ingresos NUMERIC(15, 2),
    total_gastos NUMERIC(15, 2),
    total_ahorros NUMERIC(15, 2),
    balance_final NUMERIC(15, 2)
)
AS
DECLARE VARIABLE v_presupuesto_usuario INTEGER;
DECLARE VARIABLE v_estado VARCHAR(20);
BEGIN
    IF (FN_VALIDAR_VIGENCIA_PRESUPUESTO(:p_anio, :p_mes, :p_id_presupuesto) = 0) THEN
        EXCEPTION ex_presupuesto_fuera_vigencia;

    SELECT id_usuario, estado
    FROM PRESUPUESTO
    WHERE id_presupuesto = :p_id_presupuesto
    INTO :v_presupuesto_usuario, :v_estado;

    IF (v_presupuesto_usuario IS NULL) THEN
        EXCEPTION ex_presupuesto_no_encontrado;

    IF (v_presupuesto_usuario <> p_id_usuario) THEN
        EXCEPTION ex_presupuesto_usuario;

    IF (v_estado <> 'activo') THEN
        EXCEPTION ex_presupuesto_estado;

    SELECT
        COALESCE(SUM(CASE WHEN tipo = 'ingreso' THEN monto ELSE 0 END), 0),
        COALESCE(SUM(CASE WHEN tipo = 'gasto' THEN monto ELSE 0 END), 0),
        COALESCE(SUM(CASE WHEN tipo = 'ahorro' THEN monto ELSE 0 END), 0)
    FROM TRANSACCIONES
    WHERE id_usuario = :p_id_usuario
      AND presupuesto_id = :p_id_presupuesto
      AND anio = :p_anio
      AND mes = :p_mes
      AND estado = 'activo'
    INTO :total_ingresos, :total_gastos, :total_ahorros;

    balance_final = total_ingresos - total_gastos - total_ahorros;

    SUSPEND;
END#


CREATE PROCEDURE SP_CALCULAR_MONTO_EJECUTADO_MES (
    p_id_subcategoria INTEGER,
    p_id_presupuesto INTEGER,
    p_anio INTEGER,
    p_mes INTEGER
)
RETURNS (
    monto_ejecutado NUMERIC(15, 2)
)
AS
BEGIN
    monto_ejecutado = FN_CALCULAR_MONTO_EJECUTADO(:p_id_subcategoria, :p_id_presupuesto, :p_anio, :p_mes);
    SUSPEND;
END#


CREATE PROCEDURE SP_CALCULAR_PORCENTAJE_EJECUCION_MES (
    p_id_subcategoria INTEGER,
    p_id_presupuesto INTEGER,
    p_anio INTEGER,
    p_mes INTEGER
)
RETURNS (
    porcentaje NUMERIC(9, 4)
)
AS
BEGIN
    porcentaje = FN_CALCULAR_PORCENTAJE_EJECUTADO(:p_id_subcategoria, :p_id_presupuesto, :p_anio, :p_mes);
    SUSPEND;
END#


CREATE PROCEDURE SP_CERRAR_PRESUPUESTO (
    p_id_presupuesto INTEGER,
    p_modificado_por INTEGER
)
RETURNS (
    total_ingresos NUMERIC(15, 2),
    total_gastos NUMERIC(15, 2),
    total_ahorros NUMERIC(15, 2),
    balance_final NUMERIC(15, 2)
)
AS
DECLARE VARIABLE v_estado VARCHAR(20);
DECLARE VARIABLE v_anio_fin INTEGER;
DECLARE VARIABLE v_mes_fin INTEGER;
DECLARE VARIABLE v_anio_actual INTEGER;
DECLARE VARIABLE v_mes_actual INTEGER;
DECLARE VARIABLE v_id_usuario INTEGER;
DECLARE VARIABLE v_monto_ingresos NUMERIC(15, 2);
DECLARE VARIABLE v_monto_gastos NUMERIC(15, 2);
DECLARE VARIABLE v_monto_ahorros NUMERIC(15, 2);
BEGIN
    SELECT estado, anio_fin, mes_fin, id_usuario
    FROM PRESUPUESTO
    WHERE id_presupuesto = :p_id_presupuesto
    INTO :v_estado, :v_anio_fin, :v_mes_fin, :v_id_usuario;

    IF (v_estado IS NULL) THEN
        EXCEPTION ex_presupuesto_no_encontrado;

    IF (v_estado = 'cerrado') THEN
        EXCEPTION ex_presupuesto_estado;

    v_anio_actual = EXTRACT(YEAR FROM CURRENT_DATE);
    v_mes_actual = EXTRACT(MONTH FROM CURRENT_DATE);

    IF ((v_anio_actual * 100 + v_mes_actual) < (v_anio_fin * 100 + v_mes_fin)) THEN
        EXCEPTION ex_presupuesto_no_finalizado;

    SELECT
        COALESCE(SUM(CASE WHEN tipo = 'ingreso' THEN monto ELSE 0 END), 0),
        COALESCE(SUM(CASE WHEN tipo = 'gasto' THEN monto ELSE 0 END), 0),
        COALESCE(SUM(CASE WHEN tipo = 'ahorro' THEN monto ELSE 0 END), 0)
    FROM TRANSACCIONES
    WHERE presupuesto_id = :p_id_presupuesto
      AND estado = 'activo'
    INTO :v_monto_ingresos, :v_monto_gastos, :v_monto_ahorros;

    UPDATE PRESUPUESTO
    SET estado = 'cerrado',
        modificado_en = CURRENT_TIMESTAMP,
        modificado_por = :p_modificado_por
    WHERE id_presupuesto = :p_id_presupuesto;

    total_ingresos = v_monto_ingresos;
    total_gastos = v_monto_gastos;
    total_ahorros = v_monto_ahorros;
    balance_final = v_monto_ingresos - v_monto_gastos - v_monto_ahorros;

    SUSPEND;
END#


CREATE PROCEDURE SP_CREAR_PRESUPUESTO_COMPLETO (
    p_id_usuario INTEGER,
    p_nombre VARCHAR(255),
    p_descripcion VARCHAR(500),
    p_anio_inicio INTEGER,
    p_mes_inicio INTEGER,
    p_anio_fin INTEGER,
    p_mes_fin INTEGER,
    p_total_ingresos NUMERIC(15,2),
    p_total_gastos NUMERIC(15,2),
    p_total_ahorro NUMERIC(15,2),
    p_creado_por INTEGER
)
RETURNS (
    id_presupuesto INTEGER
)
AS
DECLARE VARIABLE v_estado VARCHAR(20);
DECLARE VARIABLE v_fecha_creacion TIMESTAMP;
DECLARE VARIABLE v_overlap INTEGER;
BEGIN
    v_estado = 'activo';
    v_fecha_creacion = CURRENT_TIMESTAMP;

    IF (p_anio_fin < p_anio_inicio) THEN
        EXCEPTION ex_presupuesto_vigencia;

    IF (p_anio_fin = p_anio_inicio AND p_mes_fin < p_mes_inicio) THEN
        EXCEPTION ex_presupuesto_vigencia;

    SELECT COUNT(1)
    FROM PRESUPUESTO
    WHERE id_usuario = :p_id_usuario
      AND estado = 'activo'
      AND ((anio_inicio * 100 + mes_inicio) <= (p_anio_fin * 100 + p_mes_fin))
      AND ((anio_fin * 100 + mes_fin) >= (p_anio_inicio * 100 + p_mes_inicio))
    INTO :v_overlap;

    IF (v_overlap > 0) THEN
        EXCEPTION ex_presupuesto_traslapado;

    INSERT INTO PRESUPUESTO (
        id_usuario,
        nombre_presupuesto,
        anio_inicio,
        mes_inicio,
        anio_fin,
        mes_fin,
        total_ingresos_planificados,
        total_gastos_planificados,
        total_ahorro_planificado,
        fecha_creacion,
        estado,
        creado_en,
        creado_por
    ) VALUES (
        :p_id_usuario,
        :p_nombre,
        :p_anio_inicio,
        :p_mes_inicio,
        :p_anio_fin,
        :p_mes_fin,
        :p_total_ingresos,
        :p_total_gastos,
        :p_total_ahorro,
        :v_fecha_creacion,
        :v_estado,
        CURRENT_TIMESTAMP,
        :p_creado_por
    )
    RETURNING id_presupuesto INTO :id_presupuesto;

    SUSPEND;
END#


CREATE PROCEDURE SP_OBTENER_RESUMEN_CATEGORIA_MES (
    p_id_categoria INTEGER,
    p_id_presupuesto INTEGER,
    p_anio INTEGER,
    p_mes INTEGER
)
RETURNS (
    monto_presupuestado NUMERIC(15, 2),
    monto_ejecutado NUMERIC(15, 2),
    porcentaje NUMERIC(9, 4)
)
AS
DECLARE VARIABLE v_presupuestado NUMERIC(15, 2);
DECLARE VARIABLE v_ejecutado NUMERIC(15, 2);
BEGIN
    v_presupuestado = FN_OBTENER_TOTAL_CATEGORIA_MES(:p_id_categoria, :p_id_presupuesto, :p_anio, :p_mes);
    v_ejecutado = FN_OBTENER_TOTAL_EJECUTADO_CATEGORIA_MES(:p_id_categoria, :p_id_presupuesto, :p_anio, :p_mes);

    monto_presupuestado = v_presupuestado;
    monto_ejecutado = v_ejecutado;

    IF (v_presupuestado = 0) THEN
        porcentaje = 0;
    ELSE
        porcentaje = (v_ejecutado / v_presupuestado) * 100;

    SUSPEND;
END#


CREATE PROCEDURE SP_PROCESAR_OBLIGACIONES_MES (
    p_id_usuario INTEGER,
    p_anio INTEGER,
    p_mes INTEGER,
    p_id_presupuesto INTEGER
)
RETURNS (
    id_obligacion INTEGER,
    nombre_obligacion VARCHAR(500),
    subcategoria_id INTEGER,
    dia_vencimiento INTEGER,
    dias_restantes INTEGER,
    alerta VARCHAR(50)
)
AS
DECLARE VARIABLE v_presupuesto_usuario INTEGER;
DECLARE VARIABLE v_estado VARCHAR(20);
DECLARE VARIABLE v_clave_inicio INTEGER;
DECLARE VARIABLE v_clave_fin INTEGER;
DECLARE VARIABLE v_clave_mes INTEGER;
DECLARE VARIABLE v_anio_inicio INTEGER;
DECLARE VARIABLE v_mes_inicio INTEGER;
DECLARE VARIABLE v_anio_fin INTEGER;
DECLARE VARIABLE v_mes_fin INTEGER;
DECLARE VARIABLE v_fecha_objetivo DATE;
DECLARE VARIABLE v_dias_restantes INTEGER;
BEGIN
    SELECT id_usuario, estado, anio_inicio, mes_inicio, anio_fin, mes_fin
    FROM PRESUPUESTO
    WHERE id_presupuesto = :p_id_presupuesto
    INTO :v_presupuesto_usuario, :v_estado, :v_anio_inicio, :v_mes_inicio, :v_anio_fin, :v_mes_fin;

    IF (v_presupuesto_usuario IS NULL) THEN
        EXCEPTION ex_presupuesto_no_encontrado;

    IF (v_presupuesto_usuario <> p_id_usuario) THEN
        EXCEPTION ex_presupuesto_usuario;

    IF (v_estado <> 'activo') THEN
        EXCEPTION ex_presupuesto_estado;

    v_clave_mes = :p_anio * 100 + :p_mes;
    v_clave_inicio = v_anio_inicio * 100 + v_mes_inicio;
    v_clave_fin = v_anio_fin * 100 + v_mes_fin;

    IF (v_clave_mes < v_clave_inicio OR v_clave_mes > v_clave_fin) THEN
        EXCEPTION ex_presupuesto_fuera_vigencia;

    FOR SELECT
            o.id,
            o.nombre,
            o.subcategoria_id,
            o.dia_mes_expiracion,
            fn_dias_hasta_vencimiento(o.id)
        FROM OBLIGACION_FIJA o
        WHERE o.id_usuario = :p_id_usuario
          AND o.is_vigente = TRUE
          AND :p_anio BETWEEN EXTRACT(YEAR FROM o.fecha_inicio) AND EXTRACT(YEAR FROM COALESCE(o.fecha_final, DATE '9999-12-31'))
    INTO
        :id_obligacion,
        :nombre_obligacion,
        :subcategoria_id,
        :dia_vencimiento,
        :dias_restantes
    DO
    BEGIN
        IF (:dias_restantes IS NULL) THEN
            alerta = 'fuera_vigencia';
        ELSE IF (:dias_restantes < 0) THEN
            alerta = 'vencida';
        ELSE IF (:dias_restantes = 0) THEN
            alerta = 'vence_hoy';
        ELSE IF (:dias_restantes <= 3) THEN
            alerta = 'por_vencer';
        ELSE
            alerta = 'programada';

        SUSPEND;
    END
END#


CREATE PROCEDURE SP_REGISTRAR_TRANSACCION_COMPLETA (
    p_id_usuario INTEGER,
    p_id_presupuesto INTEGER,
    p_anio INTEGER,
    p_mes INTEGER,
    p_id_subcategoria INTEGER,
    p_id_obligacion INTEGER,
    p_tipo VARCHAR(20),
    p_descripcion VARCHAR(500),
    p_monto NUMERIC(15, 2),
    p_fecha DATE,
    p_metodo_pago VARCHAR(30),
    p_no_factura VARCHAR(500),
    p_observaciones VARCHAR(500),
    p_creado_por INTEGER
)
RETURNS (
    id_transaccion INTEGER,
    mensaje VARCHAR(200)
)
AS
DECLARE VARIABLE v_presupuesto_usuario INTEGER;
DECLARE VARIABLE v_presupuesto_estado VARCHAR(20);
DECLARE VARIABLE v_anio_inicio INTEGER;
DECLARE VARIABLE v_mes_inicio INTEGER;
DECLARE VARIABLE v_anio_fin INTEGER;
DECLARE VARIABLE v_mes_fin INTEGER;
DECLARE VARIABLE v_tipo_categoria VARCHAR(20);
DECLARE VARIABLE v_categoria_usuario INTEGER;
DECLARE VARIABLE v_obl_usuario INTEGER;
DECLARE VARIABLE v_obl_subcategoria INTEGER;
DECLARE VARIABLE v_obl_vigente BOOLEAN;
DECLARE VARIABLE v_obl_inicio DATE;
DECLARE VARIABLE v_obl_fin DATE;
DECLARE VARIABLE v_clave_fecha INTEGER;
DECLARE VARIABLE v_clave_inicio INTEGER;
DECLARE VARIABLE v_clave_fin INTEGER;
BEGIN
    IF (p_monto IS NULL OR p_monto <= 0) THEN
        EXCEPTION ex_transaccion_monto_invalido;

    IF (p_mes IS NULL OR p_mes < 1 OR p_mes > 12) THEN
        EXCEPTION ex_transaccion_mes_invalido;

    IF (COALESCE(LOWER(p_tipo), '') <> 'ingreso' AND COALESCE(LOWER(p_tipo), '') <> 'gasto' AND COALESCE(LOWER(p_tipo), '') <> 'ahorro') THEN
        EXCEPTION ex_transaccion_tipo_invalido;

    SELECT id_usuario, estado, anio_inicio, mes_inicio, anio_fin, mes_fin
    FROM PRESUPUESTO
    WHERE id_presupuesto = :p_id_presupuesto
    INTO :v_presupuesto_usuario, :v_presupuesto_estado, :v_anio_inicio, :v_mes_inicio, :v_anio_fin, :v_mes_fin;

    IF (v_presupuesto_usuario IS NULL) THEN
        EXCEPTION ex_presupuesto_no_encontrado;

    IF (v_presupuesto_usuario <> p_id_usuario) THEN
        EXCEPTION ex_presupuesto_usuario;

    IF (v_presupuesto_estado <> 'activo') THEN
        EXCEPTION ex_presupuesto_estado;

    IF (FN_VALIDAR_VIGENCIA_PRESUPUESTO(:p_anio, :p_mes, :p_id_presupuesto) = 0) THEN
        EXCEPTION ex_presupuesto_fuera_vigencia;

    IF (p_fecha IS NULL) THEN
        EXCEPTION ex_transaccion_fecha_fuera_rango;

    v_clave_fecha = EXTRACT(YEAR FROM :p_fecha) * 100 + EXTRACT(MONTH FROM :p_fecha);
    v_clave_inicio = :v_anio_inicio * 100 + :v_mes_inicio;
    v_clave_fin = :v_anio_fin * 100 + :v_mes_fin;

    IF (v_clave_fecha < v_clave_inicio OR v_clave_fecha > v_clave_fin) THEN
        EXCEPTION ex_transaccion_fecha_fuera_rango;

    SELECT c.tipo_categoria, c.id_usuario
    FROM SUBCATEGORIA s
    JOIN CATEGORIA c ON c.id = s.categoria_id
    WHERE s.id = :p_id_subcategoria
    INTO :v_tipo_categoria, :v_categoria_usuario;

    IF (v_tipo_categoria IS NULL) THEN
        EXCEPTION ex_subcategoria_no_encontrada;

    IF (LOWER(v_tipo_categoria) <> LOWER(p_tipo)) THEN
        EXCEPTION ex_transaccion_tipo_invalido;

    IF (v_categoria_usuario <> p_id_usuario) THEN
        EXCEPTION ex_transaccion_categoria_invalida;

    IF (p_id_obligacion IS NOT NULL) THEN
    BEGIN
        SELECT id_usuario, subcategoria_id, is_vigente, fecha_inicio, COALESCE(fecha_final, DATE '9999-12-31')
        FROM OBLIGACION_FIJA
        WHERE id = :p_id_obligacion
        INTO :v_obl_usuario, :v_obl_subcategoria, :v_obl_vigente, :v_obl_inicio, :v_obl_fin;

        IF (v_obl_usuario IS NULL) THEN
            EXCEPTION ex_obligacion_no_encontrada;

        IF (v_obl_usuario <> p_id_usuario OR v_obl_subcategoria <> p_id_subcategoria OR v_obl_vigente = FALSE) THEN
            EXCEPTION ex_transaccion_obligacion_invalida;

        IF (p_fecha < v_obl_inicio OR p_fecha > v_obl_fin) THEN
            EXCEPTION ex_transaccion_obligacion_invalida;
    END

    INSERT INTO TRANSACCIONES (
        id_usuario,
        presupuesto_id,
        anio,
        mes,
        subcategoria_id,
        obligacion_id,
        tipo,
        descripcion,
        monto,
        fecha,
        metodo_pago,
        no_factura,
        observaciones,
        estado,
        creado_en,
        creado_por
    )
    VALUES (
        :p_id_usuario,
        :p_id_presupuesto,
        :p_anio,
        :p_mes,
        :p_id_subcategoria,
        :p_id_obligacion,
        LOWER(:p_tipo),
        :p_descripcion,
        :p_monto,
        :p_fecha,
        :p_metodo_pago,
        :p_no_factura,
        :p_observaciones,
        'activo',
        CURRENT_TIMESTAMP,
        :p_creado_por
    )
    RETURNING id INTO :id_transaccion;

    mensaje = 'Transaccion registrada correctamente';
    SUSPEND;
END#


CREATE  PROCEDURE SP_ACTUALIZAR_PRESUPUESTO (
    id_presupuesto INTEGER,
    id_usuario INTEGER,
    nombre_presupuesto VARCHAR(255),
    anio_inicio INTEGER,
    mes_inicio INTEGER,
    anio_fin INTEGER,
    mes_fin INTEGER,
    total_ingresos_planificados NUMERIC(15,2),
    total_gastos_planificados NUMERIC(15,2),
    total_ahorro_planificado NUMERIC(15,2),
    estado VARCHAR(20),
    modificado_en TIMESTAMP,
    modificado_por INTEGER
)
AS
BEGIN
    UPDATE PRESUPUESTO
    SET 
        id_usuario = :id_usuario,
        nombre_presupuesto = :nombre_presupuesto,
        anio_inicio = :anio_inicio,
        mes_inicio = :mes_inicio,
        anio_fin = :anio_fin,
        mes_fin = :mes_fin,
        total_ingresos_planificados = :total_ingresos_planificados,
        total_gastos_planificados = :total_gastos_planificados,
        total_ahorro_planificado = :total_ahorro_planificado,
        estado = :estado,
        modificado_en = :modificado_en,
        modificado_por = :modificado_por
    WHERE id_presupuesto = :id_presupuesto;
END#

-- SP_INSERTAR_SUBCATEGORIA
-- Inserta un nuevo registro en la tabla SUBCATEGORIA y retorna el id generado.
CREATE PROCEDURE SP_INSERTAR_SUBCATEGORIA (
    p_categoria_id INTEGER,
    p_nombre VARCHAR(500),
    p_descripcion VARCHAR(500),
    p_is_default BOOLEAN,
    p_creado_por INTEGER
)
RETURNS (
    id_subcategoria INTEGER
)
AS
DECLARE VARIABLE v_categoria_estado VARCHAR(20);
DECLARE VARIABLE v_sub_default INTEGER;
BEGIN
    SELECT estado FROM CATEGORIA WHERE id = :p_categoria_id INTO :v_categoria_estado;
    IF (v_categoria_estado IS NULL) THEN
        EXCEPTION ex_categoria_no_encontrada;

    IF (:p_is_default = TRUE) THEN
    BEGIN
        SELECT COUNT(*)
        FROM SUBCATEGORIA
        WHERE categoria_id = :p_categoria_id
          AND is_default = TRUE
        INTO :v_sub_default;

        IF (v_sub_default > 0) THEN
            EXCEPTION ex_subcategoria_default_existente;
    END
    ELSE
    BEGIN
        SELECT COUNT(*)
        FROM SUBCATEGORIA
        WHERE categoria_id = :p_categoria_id
          AND estado = 'activa'
        INTO :v_sub_default;

        IF (v_sub_default = 0) THEN
            EXCEPTION ex_categoria_sin_subcategoria;
    END

    INSERT INTO SUBCATEGORIA (
        categoria_id,
        nombre,
        descripcion,
        is_default,
        estado,
        creado_por,
        creado_en
    )
    VALUES (
        :p_categoria_id,
        :p_nombre,
        :p_descripcion,
        COALESCE(:p_is_default, FALSE),
        'activa',
        :p_creado_por,
        CURRENT_TIMESTAMP
    )
    RETURNING id INTO id_subcategoria;
    SUSPEND;
END#


-- SP_ELIMINAR_SUBCATEGORIA
-- Realiza un soft delete actualizando el campo estado a 'inactivo' en la tabla SUBCATEGORIA.
CREATE PROCEDURE SP_ELIMINAR_SUBCATEGORIA (
    p_id_subcategoria INTEGER
)
AS
DECLARE VARIABLE v_is_default BOOLEAN;
DECLARE VARIABLE v_categoria_id INTEGER;
DECLARE VARIABLE v_en_uso INTEGER;
DECLARE VARIABLE v_subs_activas INTEGER;
BEGIN
    SELECT is_default, categoria_id
    FROM SUBCATEGORIA
    WHERE id = :p_id_subcategoria
    INTO :v_is_default, :v_categoria_id;

    IF (v_is_default IS NULL) THEN
        EXCEPTION ex_subcategoria_no_encontrada;

    IF (v_is_default = TRUE) THEN
        EXCEPTION ex_subcategoria_default_no_eliminar;

    SELECT COUNT(*)
    FROM DETALLE_PRESUPUESTO
    WHERE subcategoria_id = :p_id_subcategoria
      AND estado = 'activo'
    INTO :v_en_uso;

    IF (v_en_uso > 0) THEN
        EXCEPTION ex_subcategoria_usada_detalle;

    SELECT COUNT(*)
    FROM TRANSACCIONES
    WHERE subcategoria_id = :p_id_subcategoria
    INTO :v_en_uso;

    IF (v_en_uso > 0) THEN
        EXCEPTION ex_subcategoria_usada_transaccion;

    SELECT COUNT(*)
    FROM SUBCATEGORIA
    WHERE categoria_id = :v_categoria_id
      AND estado = 'activa'
      AND id <> :p_id_subcategoria
    INTO :v_subs_activas;

    IF (v_subs_activas = 0) THEN
        EXCEPTION ex_categoria_sin_subcategoria;

    UPDATE SUBCATEGORIA
    SET estado = 'inactiva',
        modificado_en = CURRENT_TIMESTAMP
    WHERE id = :p_id_subcategoria;
END#


CREATE PROCEDURE SP_LISTAR_SUBCATEGORIAS_POR_CATEGORIA (
    p_categoria_id INTEGER
)
RETURNS (
    id INTEGER,
    categoria_id INTEGER,
    nombre VARCHAR(500),
    descripcion VARCHAR(500),
    is_default BOOLEAN,
    estado VARCHAR(20),
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    FOR SELECT 
        id,
        categoria_id,
        nombre,
        descripcion,
        is_default,
        estado,
        creado_en,
        modificado_en,
        creado_por,
        modificado_por
    FROM SUBCATEGORIA
    WHERE categoria_id = :p_categoria_id
    ORDER BY is_default DESC, nombre
    INTO 
        :id,
        :categoria_id,
        :nombre,
        :descripcion,
        :is_default,
        :estado,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por
    DO
        SUSPEND;
END#


-- SP_CONSULTAR_SUBCATEGORIA
-- Devuelve un único registro de la tabla SUBCATEGORIA según su id.
CREATE PROCEDURE SP_CONSULTAR_SUBCATEGORIA (
    p_id_subcategoria INTEGER
)
RETURNS (
    id INTEGER,
    categoria_id INTEGER,
    categoria_nombre VARCHAR(500),
    tipo_categoria VARCHAR(20),
    nombre VARCHAR(500),
    descripcion VARCHAR(500),
    is_default BOOLEAN,
    estado VARCHAR(20),
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    FOR SELECT 
        s.id,
        s.categoria_id,
        c.nombre,
        c.tipo_categoria,
        s.nombre,
        s.descripcion,
        s.is_default,
        s.estado,
        s.creado_en,
        s.modificado_en,
        s.creado_por,
        s.modificado_por
    FROM SUBCATEGORIA s
    JOIN CATEGORIA c ON c.id = s.categoria_id
    WHERE s.id = :p_id_subcategoria
    INTO 
        :id,
        :categoria_id,
        :categoria_nombre,
        :tipo_categoria,
        :nombre,
        :descripcion,
        :is_default,
        :estado,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por
    DO
        SUSPEND;
END#


-- SP_ACTUALIZAR_SUBCATEGORIA
-- Actualiza un registro existente en la tabla SUBCATEGORIA.
CREATE PROCEDURE SP_ACTUALIZAR_SUBCATEGORIA (
    p_id_subcategoria INTEGER,
    p_nombre VARCHAR(500),
    p_descripcion VARCHAR(500),
    p_estado VARCHAR(20),
    p_modificado_por INTEGER
)
AS
DECLARE VARIABLE v_is_default BOOLEAN;
BEGIN
    SELECT is_default FROM SUBCATEGORIA WHERE id = :p_id_subcategoria INTO :v_is_default;
    IF (v_is_default IS NULL) THEN
        EXCEPTION ex_subcategoria_no_encontrada;

    UPDATE SUBCATEGORIA
    SET nombre = COALESCE(:p_nombre, nombre),
        descripcion = COALESCE(:p_descripcion, descripcion),
        estado = CASE WHEN :p_estado IS NULL THEN estado ELSE :p_estado END,
        modificado_en = CURRENT_TIMESTAMP,
        modificado_por = :p_modificado_por
    WHERE id = :p_id_subcategoria;
END#


-- SP_INSERTAR_TRANSACCIONES
-- Inserta un nuevo registro en la tabla TRANSACCIONES y retorna el id generado.
CREATE PROCEDURE SP_INSERTAR_TRANSACCIONES (
    p_id_usuario INTEGER,
    p_presupuesto_id INTEGER,
    p_anio INTEGER,
    p_mes INTEGER,
    p_subcategoria_id INTEGER,
    p_obligacion_id INTEGER,
    p_tipo VARCHAR(20),
    p_descripcion VARCHAR(500),
    p_monto NUMERIC(15,2),
    p_fecha DATE,
    p_metodo_pago VARCHAR(30),
    p_no_factura VARCHAR(500),
    p_observaciones VARCHAR(500),
    p_creado_por INTEGER
)
RETURNS (
    id_transacciones INTEGER
)
AS
BEGIN
    INSERT INTO TRANSACCIONES (
        id_usuario,
        presupuesto_id,
        anio,
        mes,
        subcategoria_id,
        obligacion_id,
        tipo,
        descripcion,
        monto,
        fecha,
        metodo_pago,
        no_factura,
        observaciones,
        creado_en,
        creado_por
    )
    VALUES (
        :p_id_usuario,
        :p_presupuesto_id,
        :p_anio,
        :p_mes,
        :p_subcategoria_id,
        :p_obligacion_id,
        :p_tipo,
        :p_descripcion,
        :p_monto,
        :p_fecha,
        :p_metodo_pago,
        :p_no_factura,
        :p_observaciones,
        CURRENT_TIMESTAMP,
        :p_creado_por
    )
    RETURNING id INTO id_transacciones;
    SUSPEND;
END


-- SP_ELIMINAR_TRANSACCIONES
-- Realiza un soft delete actualizando el campo estado a 'inactivo' en la tabla TRANSACCIONES.
CREATE PROCEDURE SP_ELIMINAR_TRANSACCIONES (
    p_id_transacciones INTEGER,
    p_modificado_por INTEGER
)
AS
BEGIN
    UPDATE TRANSACCIONES
    SET estado = 'inactivo',
        modificado_en = CURRENT_TIMESTAMP,
        modificado_por = :p_modificado_por
    WHERE id = :p_id_transacciones;
END#


-- SP_LISTAR_TRANSACCIONES
-- Devuelve todos los registros de la tabla TRANSACCIONES.
CREATE PROCEDURE SP_LISTAR_TRANSACCIONES
RETURNS (
    id INTEGER,
    id_usuario INTEGER,
    presupuesto_id INTEGER,
    anio INTEGER,
    mes INTEGER,
    subcategoria_id INTEGER,
    obligacion_id INTEGER,
    tipo VARCHAR(20),
    descripcion VARCHAR(500),
    monto NUMERIC(15,2),
    fecha DATE,
    metodo_pago VARCHAR(30),
    no_factura VARCHAR(500),
    observaciones VARCHAR(500),
    estado VARCHAR(20),
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    FOR SELECT 
        id,
        id_usuario,
        presupuesto_id,
        anio,
        mes,
        subcategoria_id,
        obligacion_id,
        tipo,
        descripcion,
        monto,
        fecha,
        metodo_pago,
        no_factura,
        observaciones,
        estado,
        creado_en,
        modificado_en,
        creado_por,
        modificado_por
    FROM TRANSACCIONES
    INTO 
        :id,
        :id_usuario,
        :presupuesto_id,
        :anio,
        :mes,
        :subcategoria_id,
        :obligacion_id,
        :descripcion,
        :monto,
        :fecha,
        :no_factura,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por
    DO
        SUSPEND;
END


-- SP_CONSULTAR_TRANSACCIONES
-- Devuelve un único registro de la tabla TRANSACCIONES según su id.
CREATE PROCEDURE SP_CONSULTAR_TRANSACCIONES (
    p_id_transacciones INTEGER
)
RETURNS (
    id INTEGER,
    id_usuario INTEGER,
    presupuesto_id INTEGER,
    anio INTEGER,
    mes INTEGER,
    subcategoria_id INTEGER,
    obligacion_id INTEGER,
    tipo VARCHAR(20),
    descripcion VARCHAR(500),
    monto NUMERIC(15,2),
    fecha DATE,
    metodo_pago VARCHAR(30),
    no_factura VARCHAR(500),
    observaciones VARCHAR(500),
    estado VARCHAR(20),
    creado_en TIMESTAMP,
    modificado_en TIMESTAMP,
    creado_por INTEGER,
    modificado_por INTEGER
)
AS
BEGIN
    SELECT 
        id,
        id_usuario,
        presupuesto_id,
        anio,
        mes,
        subcategoria_id,
        obligacion_id,
        tipo,
        descripcion,
        monto,
        fecha,
        metodo_pago,
        no_factura,
        observaciones,
        estado,
        creado_en,
        modificado_en,
        creado_por,
        modificado_por
    FROM TRANSACCIONES
    WHERE id = :p_id_transacciones
    INTO 
        :id,
        :id_usuario,
        :presupuesto_id,
        :anio,
        :mes,
        :subcategoria_id,
        :obligacion_id,
        :descripcion,
        :monto,
        :fecha,
        :no_factura,
        :creado_en,
        :modificado_en,
        :creado_por,
        :modificado_por;
    IF (id IS NOT NULL) THEN
        SUSPEND;
END


-- SP_ACTUALIZAR_TRANSACCIONES
-- Actualiza un registro existente en la tabla TRANSACCIONES.
CREATE PROCEDURE SP_ACTUALIZAR_TRANSACCIONES (
    p_id_transacciones INTEGER,
    p_id_usuario INTEGER,
    p_presupuesto_id INTEGER,
    p_anio INTEGER,
    p_mes INTEGER,
    p_subcategoria_id INTEGER,
    p_obligacion_id INTEGER,
    p_tipo VARCHAR(20),
    p_descripcion VARCHAR(500),
    p_monto NUMERIC(15,2),
    p_fecha DATE,
    p_metodo_pago VARCHAR(30),
    p_no_factura VARCHAR(500),
    p_observaciones VARCHAR(500),
    p_estado VARCHAR(20),
    p_modificado_por INTEGER
)
AS
BEGIN
    UPDATE TRANSACCIONES
    SET id_usuario = :p_id_usuario,
        presupuesto_id = :p_presupuesto_id,
        anio = :p_anio,
        mes = :p_mes,
        subcategoria_id = :p_subcategoria_id,
        obligacion_id = :p_obligacion_id,
        tipo = :p_tipo,
        descripcion = :p_descripcion,
        monto = :p_monto,
        fecha = :p_fecha,
        metodo_pago = :p_metodo_pago,
        no_factura = :p_no_factura,
        observaciones = :p_observaciones,
        estado = :p_estado,
        modificado_en = CURRENT_TIMESTAMP,
        modificado_por = :p_modificado_por
    WHERE id = :p_id_transacciones;
END


CREATE PROCEDURE SP_INSERTAR_USUARIO (
    p_nombre VARCHAR(255),
    p_apellido VARCHAR(255),
    p_email VARCHAR(255),
    p_salario_mensual NUMERIC(15, 2)
) RETURNS (
    id_usuario INTEGER
) AS
BEGIN
    INSERT INTO USUARIO (
        nombre,
        apellido,
        correo_electronico,
        salario_mensual_base,
        creado_en,
        estado
    )
    VALUES (
        :p_nombre,
        :p_apellido,
        :p_email,
        :p_salario_mensual,
        CURRENT_TIMESTAMP,
        'activo'
    )
    RETURNING id_usuario INTO id_usuario;
    SUSPEND;
END#

CREATE PROCEDURE SP_ELIMINAR_USUARIO (
    p_id_usuario INTEGER
) AS
BEGIN
    UPDATE USUARIO
    SET estado = 'inactivo',
        modificado_en = CURRENT_TIMESTAMP
    WHERE id_usuario = :p_id_usuario;
END#

CREATE PROCEDURE SP_LISTAR_USUARIOS
RETURNS (
    id_usuario INTEGER,
    nombre VARCHAR(255),
    apellido VARCHAR(255),
    correo_electronico VARCHAR(255),
    salario_mensual_base NUMERIC(15, 2),
    estado VARCHAR(20)
) AS
BEGIN
    FOR SELECT id_usuario, nombre, apellido, correo_electronico, salario_mensual_base, estado
        FROM USUARIO
        INTO :id_usuario, :nombre, :apellido, :correo_electronico, :salario_mensual_base, :estado
    DO
        SUSPEND;
END#

CREATE PROCEDURE SP_CONSULTAR_USUARIO (
    p_id_usuario INTEGER
) RETURNS (
    id_usuario INTEGER,
    nombre VARCHAR(255),
    apellido VARCHAR(255),
    correo_electronico VARCHAR(255),
    salario_mensual_base NUMERIC(15, 2),
    estado VARCHAR(20)
) AS
BEGIN
    SELECT id_usuario, nombre, apellido, correo_electronico, salario_mensual_base, estado
    FROM USUARIO
    WHERE id_usuario = :p_id_usuario
    INTO :id_usuario, :nombre, :apellido, :correo_electronico, :salario_mensual_base, :estado;
    
    IF (id_usuario IS NOT NULL) THEN
        SUSPEND;
END#

CREATE PROCEDURE SP_ACTUALIZAR_USUARIO (
    p_id_usuario INTEGER,
    p_nombre VARCHAR(255),
    p_apellido VARCHAR(255),
    p_salario_mensual NUMERIC(15, 2)
) AS
BEGIN
    UPDATE USUARIO
    SET nombre = :p_nombre,
        apellido = :p_apellido,
        salario_mensual_base = :p_salario_mensual,
        modificado_en = CURRENT_TIMESTAMP
    WHERE id_usuario = :p_id_usuario;
END#

SET TERM ;#
