
ALTER TABLE SUBCATEGORIA
ADD CONSTRAINT FK_SUBCATEGORIA_CATEGORIA
FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id)
ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE PRESUPUESTO
ADD CONSTRAINT FK_PRESUPUESTO_USUARIO
FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE DETALLE_PRESUPUESTO
ADD CONSTRAINT FK_DETALLE_PRESUPUESTO_PRESUPUESTO
FOREIGN KEY (presupuesto_id) REFERENCES PRESUPUESTO(id_presupuesto)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE DETALLE_PRESUPUESTO
ADD CONSTRAINT FK_DETALLE_PRESUPUESTO_SUBCATEGORIA
FOREIGN KEY (subcategoria_id) REFERENCES SUBCATEGORIA(id)
ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE OBLIGACION_FIJA
ADD CONSTRAINT FK_OBLIGACION_FIJA_USUARIO
FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE OBLIGACION_FIJA
ADD CONSTRAINT FK_OBLIGACION_FIJA_SUBCATEGORIA
FOREIGN KEY (subcategoria_id) REFERENCES SUBCATEGORIA(id)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TRANSACCIONES
ADD CONSTRAINT FK_TRANSACCIONES_USUARIO
FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TRANSACCIONES
ADD CONSTRAINT FK_TRANSACCIONES_PRESUPUESTO
FOREIGN KEY (presupuesto_id) REFERENCES PRESUPUESTO(id_presupuesto)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TRANSACCIONES
ADD CONSTRAINT FK_TRANSACCIONES_SUBCATEGORIA
FOREIGN KEY (subcategoria_id) REFERENCES SUBCATEGORIA(id)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TRANSACCIONES
ADD CONSTRAINT FK_TRANSACCIONES_OBLIGACION_FIJA
FOREIGN KEY (obligacion_id) REFERENCES OBLIGACION_FIJA(id)
ON DELETE SET NULL ON UPDATE CASCADE;